### ISSUE TITLE
Bug: Tried 0.2.2

### ISSUE THREAD

**Issue by JacksonDutton** [RogueEdit/onlineRogueEditor#122]
**What Operating System are you on** - Windows, Ubuntu, Mac, ...
- Windows 11

**Describe the bug** - A clear and concise description of what the bug is.
- Error code 
Error in enumLoader.__load_data(). [Errno 2] No such file or directory: './data/pokemon.json'
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\New folder\onlineRogueEditor-main\src\main.py", line 192, in <module>
    main()
  File "C:\Users\Admin\Desktop\New folder\onlineRogueEditor-main\src\main.py", line 92, in main
    rogue = Rogue(session, auth_token=token, clientSessionId=session_id, headers=headers)
  File "C:\Users\Admin\Desktop\New folder\onlineRogueEditor-main\src\modules\mainLogic.py", line 76, in __init__
    self.pokemon_id_by_name, self.biomes_by_id, self.moves_by_id, self.nature_data, self.vouchers_data, self.natureSlot_data = self.enum.convert_to_enums()
  File "C:\Users\Admin\Desktop\New folder\onlineRogueEditor-main\src\utilities\enumLoader.py", line 72, in convert_to_enums
    self.pokemon_id_by_name = self.__create_enum_from_dict(self.pokemon_id_by_name['dex'], 'PokemonEnum')
TypeError: 'NoneType' object is not subscripta

**To Reproduce** - Describe the steps needed to reproduce the bug.
I have little to no knowledge of python just throught this might help you guys

**Expected behavior** A clear and concise description of what you expected to happen.
- Just a working online save editor :P Good work guys, i hope you get it working

**Screenshots** - If applicable, add screenshots to help explain your problem.

**Comment by JulianStiebler** [comment]
Reading the readme.md's helps :)
