### ISSUE TITLE
Error when Submitting Changes

### ISSUE THREAD

**Issue by jemajet** [RogueEdit/onlineRogueEditor#144]
When submitting changes (option 26), there is an error where the color for the formatter isn't set.
```bash
Command: 26
Traceback (most recent call last):
  File "/Users/jemajet/Repos/pokerogue-repos/onlineRogueEditor/src/main.py", line 247, in <module>
    main()
  File "/Users/jemajet/Repos/pokerogue-repos/onlineRogueEditor/src/main.py", line 233, in main
    func()  # Call the associated function
    ^^^^^^
  File "/Users/jemajet/Repos/pokerogue-repos/onlineRogueEditor/src/modules/mainLogic.py", line 680, in update_all
    cFormatter.print("That seemed to work! Refresh without cache (STRG+F5)")
TypeError: cFormatter.print() missing 1 required positional argument: 'text'
```

The change would be simple in line 680 of `src/mainLogic.py`. I tried to make a pull request but I think the permissions are set so only you can contribute so I wanted to bring it your attention. The change is just:
```python
                cFormatter.print(Color.GREEN, "That seemed to work! Refresh without cache (STRG+F5)")
```

**Comment by jemajet** [comment]
No worries I think I was being dumb so I would be able to make PR's here I just forgot to fork.
